### ISSUE TITLE
How do I get the real fee of the transaction

### ISSUE THREAD

**Issue by Wangmmx** [fioprotocol/fio#350] opened 2022-04-20 08:41 UTC
Hello, I got the block data through the `get_block` interface of the block, which contains some information of the transaction body. I found that I can only get the `max_fee`, and sometimes the actual fee of transaction is smaller than the max_fee. I want to get the exact fee, what should I do? 

I read the interface of `get_fee`, which requires `end_point` and `fio_address`, I tried with the error 'No such FIO address', I don't quite understand. Is there a way to get the real fee of a transaction through transaction hash or other block interfaces?

**Comment by Wangmmx** [comment] 2022-04-20 10:22
FIO Address is FIO8iPiMWognLyWoiwMqG1cTufzKb8xafUGXDQwaPDfio2hY83Bk5 or rvwtjriizg31? Haven't find any short address with @, https://fio.bloks.io/account/rvwtjriizg31

**Comment by ericbutz** [comment] 2022-04-20 13:53
get_fee is the way to go. The FIO Crypto Handle (FIO Address) parameter is only required for endpoints actions that require a FIO Address as a parameter. For the endpoints where , if the user has "bundles" remaining, the cost will be zero (when a user acquires a FIO Address, they get 100 bundles that can be used to "pay" for some transactions). 

These might help:

https://developers.fioprotocol.io/pages/api/fio-api/#post-/get_fee
https://developers.fioprotocol.io/docs/fio-protocol/fio-fees

Here is an example call:

curl -s -XPOST https://fio.blockpane.com/v1/chain/get_fee -d '{
  "end_point": "transfer_tokens_pub_key"
}'

**Comment by Wangmmx** [comment] 2022-04-20 14:41
Thanks for the reply, I tried to use the `get_fee` api but can not get the fee I want.
For example, in this transaction https://fio.bloks.io/transaction/86de9d5323f27da81cb01a719b7df6851450e988a42bb6aaeec1117e3fc06800, It costs 0.866597229 FIO, but I can only get the maxFee which is 0.868837959 FIO , how can I get the right fee 0.866597229 FIO?

**Comment by ericbutz** [comment] 2022-04-21 19:21
Thanks for the additional detail. Looks like this could be a bug. Assigned and tracking in Jira as: https://fioprotocol.atlassian.net/browse/BD-3657

**Comment by Wangmmx** [comment] 2022-04-25 12:12
Ok, then I'll wait for it

**Comment by ericbutz** [comment] 2022-05-06 20:34
@Wangmmx I have been trying to reproduce internally and on Testnet. Note that there is some variability of fees on the chain due to the design of fee calculation. Block producers set a "multiplier" to their fees to make sure that fees to not get too out of line as the price of FIO changes. More information on how BPs set fees is here: 

https://developers.fioprotocol.io/docs/bp/fee-setting

Because of this you may want to add 10% to the max_fee if you are pulling the fee from get_fee to account for possible short term volatility.  Honestly, this should only rarely happen where the fee changes between the time get_fee is called and the transaction happens. 

Can you try again and see if you are still seeing the issue with get_fee?

**Comment by ericbutz** [comment] 2022-12-01 17:58
No new comments for several months. Closing.

**Closed by ericbutz** 2022-12-01 17:58 UTC
Labels: bug
